### PR TITLE
Added specifying of Success/Fail redirect method

### PR DESCRIPTION
**Pull request by hiqsol**
Your lib is done really nice :)
What we really miss is the ability to set Success/Fail method to POST.
Hope you'll accept this pull request.
If you're ok with the proposed code I can add tests for it.

### CODE REVIEW

**Comment by dercoder** [comment]
Thx. 
Travic check failed but i will add your changes today

**Comment by hiqsol** [comment]
Thank you for quick answer.
I have fixed the problem with naming.

**Comment by hiqsol** [comment]
And with array declaration too.

**Comment by hiqsol** [comment]
Shall I add tests?

**Comment by hiqsol** [comment]
Added tests.

**Comment by dercoder** [comment]
Thx for your pull request

**Pull request merged**
