### PR TITLE
Added CompletePurchaseResponse::getCurrency

### PR DESCRIPTION
**Pull request by hiqsol**
Returns currency by the merchant purse provided in the response.

### CODE REVIEW

**Comment by hiqsol** [comment]
There is a problem with Travis build because `satooshi/php-coveralls` package requires PHP 5.5 since latest 1.0.1 version.
There are two options:

1. use exact 1.0.0 version for `satooshi/php-coveralls` in composer.json
2. use allow_failures in .travis.yml for PHP 5.3 and 5.4

**Comment by dercoder** [comment]
Please change php-coveralls version to 1.0.0

**Comment by hiqsol** [comment]
Build ok. Ready for merge.

**Comment by dercoder** [comment]
Thx

**Pull request merged**
